# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20171220_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 3, 10, 38, 827625, tzinfo=utc)),
        ),
    ]
