# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 05:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20171220_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 5, 35, 57, 812423, tzinfo=utc)),
        ),
    ]
